### ISSUE TITLE
Problem with private browsing on iOS/Safari

### ISSUE THREAD

**Issue by tinny77** [obihill/restive.js#1]
Restive, while on iOS with Provate browsing mode enabled, makes the site to just show infinite alerts and force you to close Safari. Tried both full and minified version of JS, with multiple iPads and iPhones.

**Comment by schweeneh** [comment]
This is still happening on iOS Safari with private browsing turned on. The easiest way for me to reproduce it is to navigate to a page that uses restive and then physically turn the phone from upright to on its side (from portrait to landscape). Once you do this, the site will keep showing infinite alerts. 

Debugging the code I see that the issue is that the function store_func is undefined. I haven't done any further debugging to see if I can determine why the function is undefined.

**Comment by obihill** [comment]
A few questions:

1. What version of iOS are you testing this on?
2. What device?
3. Can you share the code?

Thanks.

**Comment by schweeneh** [comment]
Thanks for the prompt reply, really sorry for not getting back to you sooner, I must have missed the notification email.

I'm testing this on:
Model: iPad Air ME993LL/B
iOS: 9.2.1

Here's the JavaScript we're running:
  ```
$('body').restive({
    breakpoints: ['320', '480', '640', '960', '10000'],
    classes: ['css-320', 'css-480', 'css-640', 'css-960', 'nb'],
    turbo_classes: 'is_pc=desktop,is_mobile=mobi,is_phone=phone,is_tablet=tablet,is_landscape=landscape',
    force_dip: true
  });

  if ($.restive.getPlatform() == 'ios') {
    this.addClass("ios");
  }
```

**Comment by obihill** [comment]
Hi. No problem about the delay.

I tried your code verbatim on a Mac OS X in a private Safari browser window. I confirmed that private browsing was being detected using a `console.log` inside the `catch` block of the `_detectPrivateBrowsing` method.

However, there were no other errors and everything seems to work ok. I'm using Restive.JS version 1.3.6 (the latest version) and JQuery 1.9.1 to test.

Are you using the latest version of Restive.JS? What error messages are you getting?

Thanks.
